USE FamilyBasket
GO

CREATE TABLE dbo.SKU(
	ID INT IDENTITY(1,1),
	Code AS ('s'+ CONVERT([varchar], [ID])) UNIQUE,
	[Name] NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_SKU_ID PRIMARY KEY CLUSTERED (ID))
GO

CREATE TABLE dbo.Family(
	ID int IDENTITY(1,1),
	SurName nvarchar(100) NOT NULL,
	BudgetValue decimal(10, 2) NOT NULL,
	CONSTRAINT PK_Family_ID PRIMARY KEY CLUSTERED (ID))
GO

CREATE TABLE dbo.Basket(
	ID int IDENTITY(1,1),
	ID_SKU int NOT NULL,
	ID_Family int NOT NULL,
	Quantity int NOT NULL CONSTRAINT CHK_Quantity CHECK (Quantity >= 0),
	[Value] decimal(10, 2) NOT NULL CONSTRAINT CHK_Value CHECK (Value >= 0),
	PurchaseDate datetime NOT NULL CONSTRAINT DF_PurchaseDate DEFAULT GETDATE(),
	DiscountValue decimal(10, 2) NULL,
	CONSTRAINT PK_Basket PRIMARY KEY CLUSTERED (ID))
GO

ALTER TABLE dbo.Basket  WITH CHECK ADD CONSTRAINT FK_Basket_SKU FOREIGN KEY(ID_SKU)
REFERENCES dbo.SKU (ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE dbo.Basket CHECK CONSTRAINT FK_Basket_SKU
GO

ALTER TABLE dbo.Basket  WITH CHECK ADD  CONSTRAINT FK_Basket_Family FOREIGN KEY(ID_Family)
REFERENCES dbo.Family (ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE dbo.Basket CHECK CONSTRAINT FK_Basket_Family
GO




